/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                    isOptional: true,
                }, name: {
                    name: "name",
                    type: "String",
                    isOptional: true,
                }, avatarUrl: {
                    name: "avatarUrl",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, supabaseUid: {
                    name: "supabaseUid",
                    type: "String",
                    isOptional: true,
                }, emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    isOptional: true,
                }, companyId: {
                    name: "companyId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'company',
                }, company: {
                    name: "company",
                    type: "Company",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'owner',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "companyId" },
                }, companies: {
                    name: "companies",
                    type: "Company",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'owner',
                }, accounts: {
                    name: "accounts",
                    type: "Account",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, sessions: {
                    name: "sessions",
                    type: "Session",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                }, supabaseUid: {
                    name: "supabaseUid",
                    fields: ["supabaseUid"]
                },
            },
        },
        company: {
            name: 'Company', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, registrationNumber: {
                    name: "registrationNumber",
                    type: "String",
                }, taxId: {
                    name: "taxId",
                    type: "String",
                }, externalId: {
                    name: "externalId",
                    type: "String",
                    isOptional: true,
                }, address: {
                    name: "address",
                    type: "Json",
                    isOptional: true,
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'owner',
                }, stripeCustomerId: {
                    name: "stripeCustomerId",
                    type: "String",
                    isOptional: true,
                }, stripeSubscriptionId: {
                    name: "stripeSubscriptionId",
                    type: "String",
                    isOptional: true,
                }, stripePriceId: {
                    name: "stripePriceId",
                    type: "String",
                    isOptional: true,
                }, subscriptionTier: {
                    name: "subscriptionTier",
                    type: "Tier",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, subscriptionStatus: {
                    name: "subscriptionStatus",
                    type: "StripeSubscriptionStatus",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, subscriptionCurrentPeriodEnd: {
                    name: "subscriptionCurrentPeriodEnd",
                    type: "DateTime",
                    isOptional: true,
                }, subscriptionCancelAtPeriodEnd: {
                    name: "subscriptionCancelAtPeriodEnd",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, status: {
                    name: "status",
                    type: "CompanyStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, owner: {
                    name: "owner",
                    type: "User",
                    isDataModel: true,
                    backLink: 'companies',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, users: {
                    name: "users",
                    type: "User",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'company',
                }, employees: {
                    name: "employees",
                    type: "Employee",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'company',
                }, payrollRuns: {
                    name: "payrollRuns",
                    type: "PayrollRun",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'company',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, externalId: {
                    name: "externalId",
                    fields: ["externalId"]
                }, stripeCustomerId: {
                    name: "stripeCustomerId",
                    fields: ["stripeCustomerId"]
                }, stripeSubscriptionId: {
                    name: "stripeSubscriptionId",
                    fields: ["stripeSubscriptionId"]
                },
            },
        },
        account: {
            name: 'Account', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, type: {
                    name: "type",
                    type: "String",
                }, provider: {
                    name: "provider",
                    type: "String",
                }, providerAccountId: {
                    name: "providerAccountId",
                    type: "String",
                }, refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    isOptional: true,
                }, access_token: {
                    name: "access_token",
                    type: "String",
                    isOptional: true,
                }, expires_at: {
                    name: "expires_at",
                    type: "Int",
                    isOptional: true,
                }, token_type: {
                    name: "token_type",
                    type: "String",
                    isOptional: true,
                }, scope: {
                    name: "scope",
                    type: "String",
                    isOptional: true,
                }, id_token: {
                    name: "id_token",
                    type: "String",
                    isOptional: true,
                }, session_state: {
                    name: "session_state",
                    type: "String",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'accounts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, provider_providerAccountId: {
                    name: "provider_providerAccountId",
                    fields: ["provider", "providerAccountId"]
                },
            },
        },
        session: {
            name: 'Session', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sessionToken: {
                    name: "sessionToken",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, expires: {
                    name: "expires",
                    type: "DateTime",
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'sessions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "userId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, sessionToken: {
                    name: "sessionToken",
                    fields: ["sessionToken"]
                },
            },
        },
        verificationToken: {
            name: 'VerificationToken', fields: {
                identifier: {
                    name: "identifier",
                    type: "String",
                }, token: {
                    name: "token",
                    type: "String",
                    isId: true,
                }, expires: {
                    name: "expires",
                    type: "DateTime",
                },
            }, uniqueConstraints: {
                token: {
                    name: "token",
                    fields: ["token"]
                }, identifier_token: {
                    name: "identifier_token",
                    fields: ["identifier", "token"]
                },
            },
        },
        employee: {
            name: 'Employee', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, firstName: {
                    name: "firstName",
                    type: "String",
                }, lastName: {
                    name: "lastName",
                    type: "String",
                }, email: {
                    name: "email",
                    type: "String",
                }, iban: {
                    name: "iban",
                    type: "String",
                }, taxId: {
                    name: "taxId",
                    type: "String",
                    isOptional: true,
                }, employmentType: {
                    name: "employmentType",
                    type: "EmploymentType",
                }, salaryGross: {
                    name: "salaryGross",
                    type: "Decimal",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, salary: {
                    name: "salary",
                    type: "Float",
                }, startDate: {
                    name: "startDate",
                    type: "DateTime",
                }, endDate: {
                    name: "endDate",
                    type: "DateTime",
                    isOptional: true,
                }, companyId: {
                    name: "companyId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'company',
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, encVersion: {
                    name: "encVersion",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "v1" }] }],
                }, benefits: {
                    name: "benefits",
                    type: "Benefit",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'employee',
                }, company: {
                    name: "company",
                    type: "Company",
                    isDataModel: true,
                    backLink: 'employees',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "companyId" },
                }, payrollEntries: {
                    name: "payrollEntries",
                    type: "PayrollEntry",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'employee',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                },
            },
        },
        payrollRun: {
            name: 'PayrollRun', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, periodStart: {
                    name: "periodStart",
                    type: "DateTime",
                }, periodEnd: {
                    name: "periodEnd",
                    type: "DateTime",
                }, status: {
                    name: "status",
                    type: "PayrollStatus",
                }, companyId: {
                    name: "companyId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'company',
                }, submissionReference: {
                    name: "submissionReference",
                    type: "String",
                    isOptional: true,
                }, submittedAt: {
                    name: "submittedAt",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, entries: {
                    name: "entries",
                    type: "PayrollEntry",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'payrollRun',
                }, company: {
                    name: "company",
                    type: "Company",
                    isDataModel: true,
                    backLink: 'payrollRuns',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "companyId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, companyId_periodStart_periodEnd: {
                    name: "companyId_periodStart_periodEnd",
                    fields: ["companyId", "periodStart", "periodEnd"]
                },
            },
        },
        payrollEntry: {
            name: 'PayrollEntry', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, payrollRunId: {
                    name: "payrollRunId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'payrollRun',
                }, employeeId: {
                    name: "employeeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'employee',
                }, salaryGross: {
                    name: "salaryGross",
                    type: "Decimal",
                }, tax: {
                    name: "tax",
                    type: "Decimal",
                }, socialSecurity: {
                    name: "socialSecurity",
                    type: "Decimal",
                }, netPay: {
                    name: "netPay",
                    type: "Decimal",
                }, totalCost: {
                    name: "totalCost",
                    type: "Decimal",
                }, notes: {
                    name: "notes",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, contributions: {
                    name: "contributions",
                    type: "Contribution",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'payrollEntry',
                }, employee: {
                    name: "employee",
                    type: "Employee",
                    isDataModel: true,
                    backLink: 'payrollEntries',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "employeeId" },
                }, payrollRun: {
                    name: "payrollRun",
                    type: "PayrollRun",
                    isDataModel: true,
                    backLink: 'entries',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "payrollRunId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, payrollRunId_employeeId: {
                    name: "payrollRunId_employeeId",
                    fields: ["payrollRunId", "employeeId"]
                },
            },
        },
        contribution: {
            name: 'Contribution', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, payrollEntryId: {
                    name: "payrollEntryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'payrollEntry',
                }, type: {
                    name: "type",
                    type: "ContributionType",
                }, amount: {
                    name: "amount",
                    type: "Decimal",
                }, description: {
                    name: "description",
                    type: "String",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, payrollEntry: {
                    name: "payrollEntry",
                    type: "PayrollEntry",
                    isDataModel: true,
                    backLink: 'contributions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "payrollEntryId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        benefit: {
            name: 'Benefit', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, employeeId: {
                    name: "employeeId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'employee',
                }, type: {
                    name: "type",
                    type: "BenefitType",
                }, value: {
                    name: "value",
                    type: "Decimal",
                }, effectiveDate: {
                    name: "effectiveDate",
                    type: "DateTime",
                }, endDate: {
                    name: "endDate",
                    type: "DateTime",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, employee: {
                    name: "employee",
                    type: "Employee",
                    isDataModel: true,
                    backLink: 'benefits',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "employeeId" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        taxBracket: {
            name: 'TaxBracket', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, year: {
                    name: "year",
                    type: "Int",
                }, minIncome: {
                    name: "minIncome",
                    type: "Decimal",
                }, maxIncome: {
                    name: "maxIncome",
                    type: "Decimal",
                    isOptional: true,
                }, rate: {
                    name: "rate",
                    type: "Decimal",
                }, effectiveFrom: {
                    name: "effectiveFrom",
                    type: "DateTime",
                }, effectiveTo: {
                    name: "effectiveTo",
                    type: "DateTime",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, year_minIncome: {
                    name: "year_minIncome",
                    fields: ["year", "minIncome"]
                },
            },
        },
        socialSecurityRate: {
            name: 'SocialSecurityRate', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, year: {
                    name: "year",
                    type: "Int",
                }, employeeRate: {
                    name: "employeeRate",
                    type: "Decimal",
                }, employerRate: {
                    name: "employerRate",
                    type: "Decimal",
                }, maxWeeklyEarning: {
                    name: "maxWeeklyEarning",
                    type: "Decimal",
                }, effectiveFrom: {
                    name: "effectiveFrom",
                    type: "DateTime",
                }, effectiveTo: {
                    name: "effectiveTo",
                    type: "DateTime",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, year: {
                    name: "year",
                    fields: ["year"]
                },
            },
        },
        optimization: {
            name: 'Optimization', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, companyId: {
                    name: "companyId",
                    type: "String",
                }, suggestedAt: {
                    name: "suggestedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, type: {
                    name: "type",
                    type: "OptimizationType",
                }, description: {
                    name: "description",
                    type: "String",
                }, estimatedSaving: {
                    name: "estimatedSaving",
                    type: "Decimal",
                }, status: {
                    name: "status",
                    type: "OptimizationStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, appliedAt: {
                    name: "appliedAt",
                    type: "DateTime",
                    isOptional: true,
                }, employeeId: {
                    name: "employeeId",
                    type: "String",
                    isOptional: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        auditEvent: {
            name: 'AuditEvent', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, companyId: {
                    name: "companyId",
                    type: "String",
                }, userId: {
                    name: "userId",
                    type: "String",
                    isOptional: true,
                }, action: {
                    name: "action",
                    type: "String",
                }, resource: {
                    name: "resource",
                    type: "String",
                    isOptional: true,
                }, resourceId: {
                    name: "resourceId",
                    type: "String",
                    isOptional: true,
                }, metadata: {
                    name: "metadata",
                    type: "Json",
                    isOptional: true,
                }, ip: {
                    name: "ip",
                    type: "String",
                    isOptional: true,
                }, userAgent: {
                    name: "userAgent",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {
        user: ['Account', 'Session'],
        company: ['Employee'],

    },
    authModel: 'User'

};
export default metadata;
