/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateAuditEvent(options?: MutationOptions<Prisma.AuditEventGetPayload<Prisma.AuditEventCreateArgs> | undefined, unknown, Prisma.AuditEventCreateArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventCreateArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.AuditEventGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyAuditEvent(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.AuditEventCreateManyArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyAuditEvent<T extends Prisma.AuditEventFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.AuditEventFindManyArgs>, options?: QueryOptions<Array<Prisma.AuditEventGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('AuditEvent', 'findMany', args, options);
}

export function useInfiniteFindManyAuditEvent<T extends Prisma.AuditEventFindManyArgs, R extends Array<Prisma.AuditEventGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.AuditEventFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.AuditEventGetPayload<T>>>) {
    return request.useInfiniteModelQuery('AuditEvent', 'findMany', getNextArgs, options);
}

export function useFindUniqueAuditEvent<T extends Prisma.AuditEventFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.AuditEventFindUniqueArgs>, options?: QueryOptions<Prisma.AuditEventGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('AuditEvent', 'findUnique', args, options);
}

export function useFindFirstAuditEvent<T extends Prisma.AuditEventFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.AuditEventFindFirstArgs>, options?: QueryOptions<Prisma.AuditEventGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('AuditEvent', 'findFirst', args, options);
}

export function useUpdateAuditEvent(options?: MutationOptions<Prisma.AuditEventGetPayload<Prisma.AuditEventUpdateArgs> | undefined, unknown, Prisma.AuditEventUpdateArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.AuditEventGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyAuditEvent(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.AuditEventUpdateManyArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertAuditEvent(options?: MutationOptions<Prisma.AuditEventGetPayload<Prisma.AuditEventUpsertArgs> | undefined, unknown, Prisma.AuditEventUpsertArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.AuditEventGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteAuditEvent(options?: MutationOptions<Prisma.AuditEventGetPayload<Prisma.AuditEventDeleteArgs> | undefined, unknown, Prisma.AuditEventDeleteArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.AuditEventGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyAuditEvent(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.AuditEventDeleteManyArgs>) {
    const mutation = request.useModelMutation('AuditEvent', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.AuditEventDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.AuditEventDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateAuditEvent<T extends Prisma.AuditEventAggregateArgs>(args?: Prisma.Subset<T, Prisma.AuditEventAggregateArgs>, options?: QueryOptions<Prisma.GetAuditEventAggregateType<T>>) {
    return request.useModelQuery('AuditEvent', 'aggregate', args, options);
}

export function useGroupByAuditEvent<T extends Prisma.AuditEventGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.AuditEventGroupByArgs['orderBy'] } : { orderBy?: Prisma.AuditEventGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.AuditEventGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.AuditEventGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.AuditEventGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.AuditEventGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.AuditEventGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('AuditEvent', 'groupBy', args, options);
}

export function useCountAuditEvent<T extends Prisma.AuditEventCountArgs>(args?: Prisma.Subset<T, Prisma.AuditEventCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.AuditEventCountAggregateOutputType> : number>) {
    return request.useModelQuery('AuditEvent', 'count', args, options);
}

export function useCheckAuditEvent(args: { operation: PolicyCrudKind; where?: { id?: string; companyId?: string; userId?: string; action?: string; resource?: string; resourceId?: string; ip?: string; userAgent?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('AuditEvent', 'check', args, options);
}
