/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateBenefit(options?: MutationOptions<Prisma.BenefitGetPayload<Prisma.BenefitCreateArgs> | undefined, unknown, Prisma.BenefitCreateArgs>) {
    const mutation = request.useModelMutation('Benefit', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitCreateArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BenefitGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyBenefit(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.BenefitCreateManyArgs>) {
    const mutation = request.useModelMutation('Benefit', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyBenefit<T extends Prisma.BenefitFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.BenefitFindManyArgs>, options?: QueryOptions<Array<Prisma.BenefitGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Benefit', 'findMany', args, options);
}

export function useInfiniteFindManyBenefit<T extends Prisma.BenefitFindManyArgs, R extends Array<Prisma.BenefitGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.BenefitFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.BenefitGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Benefit', 'findMany', getNextArgs, options);
}

export function useFindUniqueBenefit<T extends Prisma.BenefitFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.BenefitFindUniqueArgs>, options?: QueryOptions<Prisma.BenefitGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Benefit', 'findUnique', args, options);
}

export function useFindFirstBenefit<T extends Prisma.BenefitFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.BenefitFindFirstArgs>, options?: QueryOptions<Prisma.BenefitGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Benefit', 'findFirst', args, options);
}

export function useUpdateBenefit(options?: MutationOptions<Prisma.BenefitGetPayload<Prisma.BenefitUpdateArgs> | undefined, unknown, Prisma.BenefitUpdateArgs>) {
    const mutation = request.useModelMutation('Benefit', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BenefitGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyBenefit(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.BenefitUpdateManyArgs>) {
    const mutation = request.useModelMutation('Benefit', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertBenefit(options?: MutationOptions<Prisma.BenefitGetPayload<Prisma.BenefitUpsertArgs> | undefined, unknown, Prisma.BenefitUpsertArgs>) {
    const mutation = request.useModelMutation('Benefit', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BenefitGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteBenefit(options?: MutationOptions<Prisma.BenefitGetPayload<Prisma.BenefitDeleteArgs> | undefined, unknown, Prisma.BenefitDeleteArgs>) {
    const mutation = request.useModelMutation('Benefit', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BenefitGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyBenefit(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.BenefitDeleteManyArgs>) {
    const mutation = request.useModelMutation('Benefit', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.BenefitDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.BenefitDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateBenefit<T extends Prisma.BenefitAggregateArgs>(args?: Prisma.Subset<T, Prisma.BenefitAggregateArgs>, options?: QueryOptions<Prisma.GetBenefitAggregateType<T>>) {
    return request.useModelQuery('Benefit', 'aggregate', args, options);
}

export function useGroupByBenefit<T extends Prisma.BenefitGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BenefitGroupByArgs['orderBy'] } : { orderBy?: Prisma.BenefitGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.BenefitGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.BenefitGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.BenefitGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.BenefitGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.BenefitGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('Benefit', 'groupBy', args, options);
}

export function useCountBenefit<T extends Prisma.BenefitCountArgs>(args?: Prisma.Subset<T, Prisma.BenefitCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.BenefitCountAggregateOutputType> : number>) {
    return request.useModelQuery('Benefit', 'count', args, options);
}
import type { BenefitType } from '@prisma/client';

export function useCheckBenefit(args: { operation: PolicyCrudKind; where?: { id?: string; employeeId?: string; type?: BenefitType }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Benefit', 'check', args, options);
}
