/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateCompany(options?: MutationOptions<Prisma.CompanyGetPayload<Prisma.CompanyCreateArgs> | undefined, unknown, Prisma.CompanyCreateArgs>) {
    const mutation = request.useModelMutation('Company', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyCreateArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.CompanyGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyCompany(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.CompanyCreateManyArgs>) {
    const mutation = request.useModelMutation('Company', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyCompany<T extends Prisma.CompanyFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs>, options?: QueryOptions<Array<Prisma.CompanyGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Company', 'findMany', args, options);
}

export function useInfiniteFindManyCompany<T extends Prisma.CompanyFindManyArgs, R extends Array<Prisma.CompanyGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.CompanyFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.CompanyGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Company', 'findMany', getNextArgs, options);
}

export function useFindUniqueCompany<T extends Prisma.CompanyFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.CompanyFindUniqueArgs>, options?: QueryOptions<Prisma.CompanyGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Company', 'findUnique', args, options);
}

export function useFindFirstCompany<T extends Prisma.CompanyFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.CompanyFindFirstArgs>, options?: QueryOptions<Prisma.CompanyGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Company', 'findFirst', args, options);
}

export function useUpdateCompany(options?: MutationOptions<Prisma.CompanyGetPayload<Prisma.CompanyUpdateArgs> | undefined, unknown, Prisma.CompanyUpdateArgs>) {
    const mutation = request.useModelMutation('Company', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.CompanyGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyCompany(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.CompanyUpdateManyArgs>) {
    const mutation = request.useModelMutation('Company', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertCompany(options?: MutationOptions<Prisma.CompanyGetPayload<Prisma.CompanyUpsertArgs> | undefined, unknown, Prisma.CompanyUpsertArgs>) {
    const mutation = request.useModelMutation('Company', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.CompanyGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteCompany(options?: MutationOptions<Prisma.CompanyGetPayload<Prisma.CompanyDeleteArgs> | undefined, unknown, Prisma.CompanyDeleteArgs>) {
    const mutation = request.useModelMutation('Company', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.CompanyGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyCompany(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.CompanyDeleteManyArgs>) {
    const mutation = request.useModelMutation('Company', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.CompanyDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.CompanyDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateCompany<T extends Prisma.CompanyAggregateArgs>(args?: Prisma.Subset<T, Prisma.CompanyAggregateArgs>, options?: QueryOptions<Prisma.GetCompanyAggregateType<T>>) {
    return request.useModelQuery('Company', 'aggregate', args, options);
}

export function useGroupByCompany<T extends Prisma.CompanyGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.CompanyGroupByArgs['orderBy'] } : { orderBy?: Prisma.CompanyGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.CompanyGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.CompanyGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.CompanyGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.CompanyGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.CompanyGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('Company', 'groupBy', args, options);
}

export function useCountCompany<T extends Prisma.CompanyCountArgs>(args?: Prisma.Subset<T, Prisma.CompanyCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.CompanyCountAggregateOutputType> : number>) {
    return request.useModelQuery('Company', 'count', args, options);
}
import type { Tier, StripeSubscriptionStatus, CompanyStatus } from '@prisma/client';

export function useCheckCompany(args: { operation: PolicyCrudKind; where?: { id?: string; name?: string; registrationNumber?: string; taxId?: string; externalId?: string; userId?: string; stripeCustomerId?: string; stripeSubscriptionId?: string; stripePriceId?: string; subscriptionTier?: Tier; subscriptionStatus?: StripeSubscriptionStatus; subscriptionCancelAtPeriodEnd?: boolean; status?: CompanyStatus }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Company', 'check', args, options);
}
