/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateContribution(options?: MutationOptions<Prisma.ContributionGetPayload<Prisma.ContributionCreateArgs> | undefined, unknown, Prisma.ContributionCreateArgs>) {
    const mutation = request.useModelMutation('Contribution', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionCreateArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.ContributionGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyContribution(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.ContributionCreateManyArgs>) {
    const mutation = request.useModelMutation('Contribution', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyContribution<T extends Prisma.ContributionFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.ContributionFindManyArgs>, options?: QueryOptions<Array<Prisma.ContributionGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Contribution', 'findMany', args, options);
}

export function useInfiniteFindManyContribution<T extends Prisma.ContributionFindManyArgs, R extends Array<Prisma.ContributionGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.ContributionFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.ContributionGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Contribution', 'findMany', getNextArgs, options);
}

export function useFindUniqueContribution<T extends Prisma.ContributionFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.ContributionFindUniqueArgs>, options?: QueryOptions<Prisma.ContributionGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Contribution', 'findUnique', args, options);
}

export function useFindFirstContribution<T extends Prisma.ContributionFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.ContributionFindFirstArgs>, options?: QueryOptions<Prisma.ContributionGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Contribution', 'findFirst', args, options);
}

export function useUpdateContribution(options?: MutationOptions<Prisma.ContributionGetPayload<Prisma.ContributionUpdateArgs> | undefined, unknown, Prisma.ContributionUpdateArgs>) {
    const mutation = request.useModelMutation('Contribution', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.ContributionGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyContribution(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.ContributionUpdateManyArgs>) {
    const mutation = request.useModelMutation('Contribution', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertContribution(options?: MutationOptions<Prisma.ContributionGetPayload<Prisma.ContributionUpsertArgs> | undefined, unknown, Prisma.ContributionUpsertArgs>) {
    const mutation = request.useModelMutation('Contribution', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.ContributionGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteContribution(options?: MutationOptions<Prisma.ContributionGetPayload<Prisma.ContributionDeleteArgs> | undefined, unknown, Prisma.ContributionDeleteArgs>) {
    const mutation = request.useModelMutation('Contribution', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.ContributionGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyContribution(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.ContributionDeleteManyArgs>) {
    const mutation = request.useModelMutation('Contribution', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.ContributionDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.ContributionDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateContribution<T extends Prisma.ContributionAggregateArgs>(args?: Prisma.Subset<T, Prisma.ContributionAggregateArgs>, options?: QueryOptions<Prisma.GetContributionAggregateType<T>>) {
    return request.useModelQuery('Contribution', 'aggregate', args, options);
}

export function useGroupByContribution<T extends Prisma.ContributionGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ContributionGroupByArgs['orderBy'] } : { orderBy?: Prisma.ContributionGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.ContributionGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.ContributionGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.ContributionGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.ContributionGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.ContributionGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('Contribution', 'groupBy', args, options);
}

export function useCountContribution<T extends Prisma.ContributionCountArgs>(args?: Prisma.Subset<T, Prisma.ContributionCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.ContributionCountAggregateOutputType> : number>) {
    return request.useModelQuery('Contribution', 'count', args, options);
}
import type { ContributionType } from '@prisma/client';

export function useCheckContribution(args: { operation: PolicyCrudKind; where?: { id?: string; payrollEntryId?: string; type?: ContributionType; description?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Contribution', 'check', args, options);
}
