/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateEmployee(options?: MutationOptions<Prisma.EmployeeGetPayload<Prisma.EmployeeCreateArgs> | undefined, unknown, Prisma.EmployeeCreateArgs>) {
    const mutation = request.useModelMutation('Employee', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeCreateArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EmployeeGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyEmployee(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EmployeeCreateManyArgs>) {
    const mutation = request.useModelMutation('Employee', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyEmployee<T extends Prisma.EmployeeFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.EmployeeFindManyArgs>, options?: QueryOptions<Array<Prisma.EmployeeGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Employee', 'findMany', args, options);
}

export function useInfiniteFindManyEmployee<T extends Prisma.EmployeeFindManyArgs, R extends Array<Prisma.EmployeeGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.EmployeeFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.EmployeeGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Employee', 'findMany', getNextArgs, options);
}

export function useFindUniqueEmployee<T extends Prisma.EmployeeFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.EmployeeFindUniqueArgs>, options?: QueryOptions<Prisma.EmployeeGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Employee', 'findUnique', args, options);
}

export function useFindFirstEmployee<T extends Prisma.EmployeeFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.EmployeeFindFirstArgs>, options?: QueryOptions<Prisma.EmployeeGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Employee', 'findFirst', args, options);
}

export function useUpdateEmployee(options?: MutationOptions<Prisma.EmployeeGetPayload<Prisma.EmployeeUpdateArgs> | undefined, unknown, Prisma.EmployeeUpdateArgs>) {
    const mutation = request.useModelMutation('Employee', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EmployeeGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyEmployee(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EmployeeUpdateManyArgs>) {
    const mutation = request.useModelMutation('Employee', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertEmployee(options?: MutationOptions<Prisma.EmployeeGetPayload<Prisma.EmployeeUpsertArgs> | undefined, unknown, Prisma.EmployeeUpsertArgs>) {
    const mutation = request.useModelMutation('Employee', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EmployeeGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteEmployee(options?: MutationOptions<Prisma.EmployeeGetPayload<Prisma.EmployeeDeleteArgs> | undefined, unknown, Prisma.EmployeeDeleteArgs>) {
    const mutation = request.useModelMutation('Employee', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.EmployeeGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyEmployee(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.EmployeeDeleteManyArgs>) {
    const mutation = request.useModelMutation('Employee', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.EmployeeDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.EmployeeDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateEmployee<T extends Prisma.EmployeeAggregateArgs>(args?: Prisma.Subset<T, Prisma.EmployeeAggregateArgs>, options?: QueryOptions<Prisma.GetEmployeeAggregateType<T>>) {
    return request.useModelQuery('Employee', 'aggregate', args, options);
}

export function useGroupByEmployee<T extends Prisma.EmployeeGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EmployeeGroupByArgs['orderBy'] } : { orderBy?: Prisma.EmployeeGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.EmployeeGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.EmployeeGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.EmployeeGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.EmployeeGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.EmployeeGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('Employee', 'groupBy', args, options);
}

export function useCountEmployee<T extends Prisma.EmployeeCountArgs>(args?: Prisma.Subset<T, Prisma.EmployeeCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.EmployeeCountAggregateOutputType> : number>) {
    return request.useModelQuery('Employee', 'count', args, options);
}
import type { EmploymentType } from '@prisma/client';

export function useCheckEmployee(args: { operation: PolicyCrudKind; where?: { id?: string; firstName?: string; lastName?: string; email?: string; iban?: string; taxId?: string; employmentType?: EmploymentType; companyId?: string; encVersion?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Employee', 'check', args, options);
}
