/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateOptimization(options?: MutationOptions<Prisma.OptimizationGetPayload<Prisma.OptimizationCreateArgs> | undefined, unknown, Prisma.OptimizationCreateArgs>) {
    const mutation = request.useModelMutation('Optimization', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationCreateArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.OptimizationGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyOptimization(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.OptimizationCreateManyArgs>) {
    const mutation = request.useModelMutation('Optimization', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyOptimization<T extends Prisma.OptimizationFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.OptimizationFindManyArgs>, options?: QueryOptions<Array<Prisma.OptimizationGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('Optimization', 'findMany', args, options);
}

export function useInfiniteFindManyOptimization<T extends Prisma.OptimizationFindManyArgs, R extends Array<Prisma.OptimizationGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.OptimizationFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.OptimizationGetPayload<T>>>) {
    return request.useInfiniteModelQuery('Optimization', 'findMany', getNextArgs, options);
}

export function useFindUniqueOptimization<T extends Prisma.OptimizationFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.OptimizationFindUniqueArgs>, options?: QueryOptions<Prisma.OptimizationGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Optimization', 'findUnique', args, options);
}

export function useFindFirstOptimization<T extends Prisma.OptimizationFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.OptimizationFindFirstArgs>, options?: QueryOptions<Prisma.OptimizationGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('Optimization', 'findFirst', args, options);
}

export function useUpdateOptimization(options?: MutationOptions<Prisma.OptimizationGetPayload<Prisma.OptimizationUpdateArgs> | undefined, unknown, Prisma.OptimizationUpdateArgs>) {
    const mutation = request.useModelMutation('Optimization', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.OptimizationGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyOptimization(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.OptimizationUpdateManyArgs>) {
    const mutation = request.useModelMutation('Optimization', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertOptimization(options?: MutationOptions<Prisma.OptimizationGetPayload<Prisma.OptimizationUpsertArgs> | undefined, unknown, Prisma.OptimizationUpsertArgs>) {
    const mutation = request.useModelMutation('Optimization', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.OptimizationGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteOptimization(options?: MutationOptions<Prisma.OptimizationGetPayload<Prisma.OptimizationDeleteArgs> | undefined, unknown, Prisma.OptimizationDeleteArgs>) {
    const mutation = request.useModelMutation('Optimization', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.OptimizationGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyOptimization(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.OptimizationDeleteManyArgs>) {
    const mutation = request.useModelMutation('Optimization', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.OptimizationDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.OptimizationDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateOptimization<T extends Prisma.OptimizationAggregateArgs>(args?: Prisma.Subset<T, Prisma.OptimizationAggregateArgs>, options?: QueryOptions<Prisma.GetOptimizationAggregateType<T>>) {
    return request.useModelQuery('Optimization', 'aggregate', args, options);
}

export function useGroupByOptimization<T extends Prisma.OptimizationGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.OptimizationGroupByArgs['orderBy'] } : { orderBy?: Prisma.OptimizationGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.OptimizationGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.OptimizationGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.OptimizationGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.OptimizationGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.OptimizationGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('Optimization', 'groupBy', args, options);
}

export function useCountOptimization<T extends Prisma.OptimizationCountArgs>(args?: Prisma.Subset<T, Prisma.OptimizationCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.OptimizationCountAggregateOutputType> : number>) {
    return request.useModelQuery('Optimization', 'count', args, options);
}
import type { OptimizationType, OptimizationStatus } from '@prisma/client';

export function useCheckOptimization(args: { operation: PolicyCrudKind; where?: { id?: string; companyId?: string; type?: OptimizationType; description?: string; status?: OptimizationStatus; employeeId?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('Optimization', 'check', args, options);
}
