/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreatePayrollEntry(options?: MutationOptions<Prisma.PayrollEntryGetPayload<Prisma.PayrollEntryCreateArgs> | undefined, unknown, Prisma.PayrollEntryCreateArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryCreateArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollEntryGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyPayrollEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollEntryCreateManyArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyPayrollEntry<T extends Prisma.PayrollEntryFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollEntryFindManyArgs>, options?: QueryOptions<Array<Prisma.PayrollEntryGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('PayrollEntry', 'findMany', args, options);
}

export function useInfiniteFindManyPayrollEntry<T extends Prisma.PayrollEntryFindManyArgs, R extends Array<Prisma.PayrollEntryGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.PayrollEntryFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.PayrollEntryGetPayload<T>>>) {
    return request.useInfiniteModelQuery('PayrollEntry', 'findMany', getNextArgs, options);
}

export function useFindUniquePayrollEntry<T extends Prisma.PayrollEntryFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollEntryFindUniqueArgs>, options?: QueryOptions<Prisma.PayrollEntryGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('PayrollEntry', 'findUnique', args, options);
}

export function useFindFirstPayrollEntry<T extends Prisma.PayrollEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollEntryFindFirstArgs>, options?: QueryOptions<Prisma.PayrollEntryGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('PayrollEntry', 'findFirst', args, options);
}

export function useUpdatePayrollEntry(options?: MutationOptions<Prisma.PayrollEntryGetPayload<Prisma.PayrollEntryUpdateArgs> | undefined, unknown, Prisma.PayrollEntryUpdateArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollEntryGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyPayrollEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollEntryUpdateManyArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertPayrollEntry(options?: MutationOptions<Prisma.PayrollEntryGetPayload<Prisma.PayrollEntryUpsertArgs> | undefined, unknown, Prisma.PayrollEntryUpsertArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollEntryGetPayload<T> | undefined>;
        }
    };
}

export function useDeletePayrollEntry(options?: MutationOptions<Prisma.PayrollEntryGetPayload<Prisma.PayrollEntryDeleteArgs> | undefined, unknown, Prisma.PayrollEntryDeleteArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollEntryGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyPayrollEntry(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollEntryDeleteManyArgs>) {
    const mutation = request.useModelMutation('PayrollEntry', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollEntryDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollEntryDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregatePayrollEntry<T extends Prisma.PayrollEntryAggregateArgs>(args?: Prisma.Subset<T, Prisma.PayrollEntryAggregateArgs>, options?: QueryOptions<Prisma.GetPayrollEntryAggregateType<T>>) {
    return request.useModelQuery('PayrollEntry', 'aggregate', args, options);
}

export function useGroupByPayrollEntry<T extends Prisma.PayrollEntryGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PayrollEntryGroupByArgs['orderBy'] } : { orderBy?: Prisma.PayrollEntryGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.PayrollEntryGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.PayrollEntryGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.PayrollEntryGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.PayrollEntryGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.PayrollEntryGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('PayrollEntry', 'groupBy', args, options);
}

export function useCountPayrollEntry<T extends Prisma.PayrollEntryCountArgs>(args?: Prisma.Subset<T, Prisma.PayrollEntryCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.PayrollEntryCountAggregateOutputType> : number>) {
    return request.useModelQuery('PayrollEntry', 'count', args, options);
}

export function useCheckPayrollEntry(args: { operation: PolicyCrudKind; where?: { id?: string; payrollRunId?: string; employeeId?: string; notes?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('PayrollEntry', 'check', args, options);
}
