/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreatePayrollRun(options?: MutationOptions<Prisma.PayrollRunGetPayload<Prisma.PayrollRunCreateArgs> | undefined, unknown, Prisma.PayrollRunCreateArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunCreateArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollRunGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyPayrollRun(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollRunCreateManyArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyPayrollRun<T extends Prisma.PayrollRunFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollRunFindManyArgs>, options?: QueryOptions<Array<Prisma.PayrollRunGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('PayrollRun', 'findMany', args, options);
}

export function useInfiniteFindManyPayrollRun<T extends Prisma.PayrollRunFindManyArgs, R extends Array<Prisma.PayrollRunGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.PayrollRunFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.PayrollRunGetPayload<T>>>) {
    return request.useInfiniteModelQuery('PayrollRun', 'findMany', getNextArgs, options);
}

export function useFindUniquePayrollRun<T extends Prisma.PayrollRunFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollRunFindUniqueArgs>, options?: QueryOptions<Prisma.PayrollRunGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('PayrollRun', 'findUnique', args, options);
}

export function useFindFirstPayrollRun<T extends Prisma.PayrollRunFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.PayrollRunFindFirstArgs>, options?: QueryOptions<Prisma.PayrollRunGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('PayrollRun', 'findFirst', args, options);
}

export function useUpdatePayrollRun(options?: MutationOptions<Prisma.PayrollRunGetPayload<Prisma.PayrollRunUpdateArgs> | undefined, unknown, Prisma.PayrollRunUpdateArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollRunGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyPayrollRun(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollRunUpdateManyArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertPayrollRun(options?: MutationOptions<Prisma.PayrollRunGetPayload<Prisma.PayrollRunUpsertArgs> | undefined, unknown, Prisma.PayrollRunUpsertArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollRunGetPayload<T> | undefined>;
        }
    };
}

export function useDeletePayrollRun(options?: MutationOptions<Prisma.PayrollRunGetPayload<Prisma.PayrollRunDeleteArgs> | undefined, unknown, Prisma.PayrollRunDeleteArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.PayrollRunGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyPayrollRun(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.PayrollRunDeleteManyArgs>) {
    const mutation = request.useModelMutation('PayrollRun', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.PayrollRunDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.PayrollRunDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregatePayrollRun<T extends Prisma.PayrollRunAggregateArgs>(args?: Prisma.Subset<T, Prisma.PayrollRunAggregateArgs>, options?: QueryOptions<Prisma.GetPayrollRunAggregateType<T>>) {
    return request.useModelQuery('PayrollRun', 'aggregate', args, options);
}

export function useGroupByPayrollRun<T extends Prisma.PayrollRunGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.PayrollRunGroupByArgs['orderBy'] } : { orderBy?: Prisma.PayrollRunGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.PayrollRunGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.PayrollRunGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.PayrollRunGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.PayrollRunGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.PayrollRunGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('PayrollRun', 'groupBy', args, options);
}

export function useCountPayrollRun<T extends Prisma.PayrollRunCountArgs>(args?: Prisma.Subset<T, Prisma.PayrollRunCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.PayrollRunCountAggregateOutputType> : number>) {
    return request.useModelQuery('PayrollRun', 'count', args, options);
}
import type { PayrollStatus } from '@prisma/client';

export function useCheckPayrollRun(args: { operation: PolicyCrudKind; where?: { id?: string; status?: PayrollStatus; companyId?: string; submissionReference?: string }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('PayrollRun', 'check', args, options);
}
