/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateSocialSecurityRate(options?: MutationOptions<Prisma.SocialSecurityRateGetPayload<Prisma.SocialSecurityRateCreateArgs> | undefined, unknown, Prisma.SocialSecurityRateCreateArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateCreateArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.SocialSecurityRateGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManySocialSecurityRate(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.SocialSecurityRateCreateManyArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManySocialSecurityRate<T extends Prisma.SocialSecurityRateFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.SocialSecurityRateFindManyArgs>, options?: QueryOptions<Array<Prisma.SocialSecurityRateGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('SocialSecurityRate', 'findMany', args, options);
}

export function useInfiniteFindManySocialSecurityRate<T extends Prisma.SocialSecurityRateFindManyArgs, R extends Array<Prisma.SocialSecurityRateGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.SocialSecurityRateFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.SocialSecurityRateGetPayload<T>>>) {
    return request.useInfiniteModelQuery('SocialSecurityRate', 'findMany', getNextArgs, options);
}

export function useFindUniqueSocialSecurityRate<T extends Prisma.SocialSecurityRateFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.SocialSecurityRateFindUniqueArgs>, options?: QueryOptions<Prisma.SocialSecurityRateGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('SocialSecurityRate', 'findUnique', args, options);
}

export function useFindFirstSocialSecurityRate<T extends Prisma.SocialSecurityRateFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.SocialSecurityRateFindFirstArgs>, options?: QueryOptions<Prisma.SocialSecurityRateGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('SocialSecurityRate', 'findFirst', args, options);
}

export function useUpdateSocialSecurityRate(options?: MutationOptions<Prisma.SocialSecurityRateGetPayload<Prisma.SocialSecurityRateUpdateArgs> | undefined, unknown, Prisma.SocialSecurityRateUpdateArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.SocialSecurityRateGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManySocialSecurityRate(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.SocialSecurityRateUpdateManyArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertSocialSecurityRate(options?: MutationOptions<Prisma.SocialSecurityRateGetPayload<Prisma.SocialSecurityRateUpsertArgs> | undefined, unknown, Prisma.SocialSecurityRateUpsertArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.SocialSecurityRateGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteSocialSecurityRate(options?: MutationOptions<Prisma.SocialSecurityRateGetPayload<Prisma.SocialSecurityRateDeleteArgs> | undefined, unknown, Prisma.SocialSecurityRateDeleteArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.SocialSecurityRateGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManySocialSecurityRate(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.SocialSecurityRateDeleteManyArgs>) {
    const mutation = request.useModelMutation('SocialSecurityRate', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.SocialSecurityRateDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.SocialSecurityRateDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateSocialSecurityRate<T extends Prisma.SocialSecurityRateAggregateArgs>(args?: Prisma.Subset<T, Prisma.SocialSecurityRateAggregateArgs>, options?: QueryOptions<Prisma.GetSocialSecurityRateAggregateType<T>>) {
    return request.useModelQuery('SocialSecurityRate', 'aggregate', args, options);
}

export function useGroupBySocialSecurityRate<T extends Prisma.SocialSecurityRateGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.SocialSecurityRateGroupByArgs['orderBy'] } : { orderBy?: Prisma.SocialSecurityRateGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.SocialSecurityRateGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.SocialSecurityRateGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.SocialSecurityRateGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.SocialSecurityRateGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.SocialSecurityRateGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('SocialSecurityRate', 'groupBy', args, options);
}

export function useCountSocialSecurityRate<T extends Prisma.SocialSecurityRateCountArgs>(args?: Prisma.Subset<T, Prisma.SocialSecurityRateCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.SocialSecurityRateCountAggregateOutputType> : number>) {
    return request.useModelQuery('SocialSecurityRate', 'count', args, options);
}

export function useCheckSocialSecurityRate(args: { operation: PolicyCrudKind; where?: { id?: string; year?: number }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('SocialSecurityRate', 'check', args, options);
}
