/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma } from "@prisma/client";
import { type GetNextArgs, type QueryOptions, type InfiniteQueryOptions, type MutationOptions, type PickEnumerable } from '@zenstackhq/swr/runtime';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
import * as request from '@zenstackhq/swr/runtime';

export function useCreateTaxBracket(options?: MutationOptions<Prisma.TaxBracketGetPayload<Prisma.TaxBracketCreateArgs> | undefined, unknown, Prisma.TaxBracketCreateArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'POST', 'create', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketCreateArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketCreateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.TaxBracketGetPayload<T> | undefined>;
        }
    };
}

export function useCreateManyTaxBracket(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.TaxBracketCreateManyArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'POST', 'createMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketCreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketCreateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useFindManyTaxBracket<T extends Prisma.TaxBracketFindManyArgs>(args?: Prisma.SelectSubset<T, Prisma.TaxBracketFindManyArgs>, options?: QueryOptions<Array<Prisma.TaxBracketGetPayload<T> & { $optimistic?: boolean }>>) {
    return request.useModelQuery('TaxBracket', 'findMany', args, options);
}

export function useInfiniteFindManyTaxBracket<T extends Prisma.TaxBracketFindManyArgs, R extends Array<Prisma.TaxBracketGetPayload<T>>>(getNextArgs: GetNextArgs<Prisma.SelectSubset<T, Prisma.TaxBracketFindManyArgs> | undefined, R>, options?: InfiniteQueryOptions<Array<Prisma.TaxBracketGetPayload<T>>>) {
    return request.useInfiniteModelQuery('TaxBracket', 'findMany', getNextArgs, options);
}

export function useFindUniqueTaxBracket<T extends Prisma.TaxBracketFindUniqueArgs>(args?: Prisma.SelectSubset<T, Prisma.TaxBracketFindUniqueArgs>, options?: QueryOptions<Prisma.TaxBracketGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('TaxBracket', 'findUnique', args, options);
}

export function useFindFirstTaxBracket<T extends Prisma.TaxBracketFindFirstArgs>(args?: Prisma.SelectSubset<T, Prisma.TaxBracketFindFirstArgs>, options?: QueryOptions<Prisma.TaxBracketGetPayload<T> & { $optimistic?: boolean }>) {
    return request.useModelQuery('TaxBracket', 'findFirst', args, options);
}

export function useUpdateTaxBracket(options?: MutationOptions<Prisma.TaxBracketGetPayload<Prisma.TaxBracketUpdateArgs> | undefined, unknown, Prisma.TaxBracketUpdateArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'PUT', 'update', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketUpdateArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketUpdateArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.TaxBracketGetPayload<T> | undefined>;
        }
    };
}

export function useUpdateManyTaxBracket(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.TaxBracketUpdateManyArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'PUT', 'updateMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketUpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketUpdateManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useUpsertTaxBracket(options?: MutationOptions<Prisma.TaxBracketGetPayload<Prisma.TaxBracketUpsertArgs> | undefined, unknown, Prisma.TaxBracketUpsertArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'POST', 'upsert', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketUpsertArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketUpsertArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.TaxBracketGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteTaxBracket(options?: MutationOptions<Prisma.TaxBracketGetPayload<Prisma.TaxBracketDeleteArgs> | undefined, unknown, Prisma.TaxBracketDeleteArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'DELETE', 'delete', metadata, options, true);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketDeleteArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketDeleteArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.TaxBracketGetPayload<T> | undefined>;
        }
    };
}

export function useDeleteManyTaxBracket(options?: MutationOptions<Prisma.BatchPayload, unknown, Prisma.TaxBracketDeleteManyArgs>) {
    const mutation = request.useModelMutation('TaxBracket', 'DELETE', 'deleteMany', metadata, options, false);
    return {
        ...mutation,
        trigger: <T extends Prisma.TaxBracketDeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.TaxBracketDeleteManyArgs>) => {
            return mutation.trigger(args, options as any) as Promise<Prisma.BatchPayload>;
        }
    };
}

export function useAggregateTaxBracket<T extends Prisma.TaxBracketAggregateArgs>(args?: Prisma.Subset<T, Prisma.TaxBracketAggregateArgs>, options?: QueryOptions<Prisma.GetTaxBracketAggregateType<T>>) {
    return request.useModelQuery('TaxBracket', 'aggregate', args, options);
}

export function useGroupByTaxBracket<T extends Prisma.TaxBracketGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.TaxBracketGroupByArgs['orderBy'] } : { orderBy?: Prisma.TaxBracketGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]>(args?: Prisma.SubsetIntersection<T, Prisma.TaxBracketGroupByArgs, OrderByArg> & InputErrors, options?: QueryOptions<{} extends InputErrors ?
        Array<PickEnumerable<Prisma.TaxBracketGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof Prisma.TaxBracketGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Prisma.TaxBracketGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], Prisma.TaxBracketGroupByOutputType[P]>
        }
        > : InputErrors>) {
    return request.useModelQuery('TaxBracket', 'groupBy', args, options);
}

export function useCountTaxBracket<T extends Prisma.TaxBracketCountArgs>(args?: Prisma.Subset<T, Prisma.TaxBracketCountArgs>, options?: QueryOptions<T extends { select: any; } ? T['select'] extends true ? number : Prisma.GetScalarType<T['select'], Prisma.TaxBracketCountAggregateOutputType> : number>) {
    return request.useModelQuery('TaxBracket', 'count', args, options);
}

export function useCheckTaxBracket(args: { operation: PolicyCrudKind; where?: { id?: string; year?: number }; }, options?: QueryOptions<boolean>) {
    return request.useModelQuery('TaxBracket', 'check', args, options);
}
